name: docs-build

on:
  push:
    branches:
      - master
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      # - name: build-docs
      #   run: npm run docs:build
      - name: vuepress
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: bfclouds/blog-page
          TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm && npm docs:build
          BUILD_DIR: docs/.vuepress/dist
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v3
      #   with:
      #     repo: blog/bfclouds.github.io
      #     target_branch: pages
      #     build_dir: $BUILD_DIR
      #   env:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     TARGET_REPO: bfclouds/blog
      #     TARGET_BRANCH: pages
      #     BUILD_SCRIPT: npm && npm build
      #     BUILD_DIR: blog/.vuepress/dist/

