name: docs-build

on:
  push:
    branches:
      - master
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: build-docs
        run: ./github/workflows/blog.sh
        shell: bash
      # - name: build-docs
      #   run: npm run docs:build
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v3
        # with:
          # repo: blog/bfclouds.github.io
          # target_branch: master
          # build_dir: docs/.vuepress/dist
        # env:
        #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        #   TARGET_REPO: username/repo
        #   TARGET_BRANCH: master
        #   BUILD_SCRIPT: npm && npm build
        #   BUILD_DIR: blog/.vuepress/dist/

